### ISSUE TITLE
Question regarding MultiMC (no issue tracker on GitHub)

### ISSUE THREAD

**Issue by mrtajniak** [Ponywka/SteamAccountSwitcher#1]
Hi, will you update your modded MultiMC version? By the way, I have a problem with the "Download all" button

**Comment by Ponywka** [comment]
"Download all"? What's you mean? 
I think I can do it, just now I haven't time for it. Anyway I can try do it today

**Comment by mrtajniak** [comment]
No problem, you don't have to do that right now. If you have a moment, then do it, the launcher itself works without any problems
